# Generated by Django 3.1.7 on 2021-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0002_user_recipe_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipe_list',
            name='list_recipe',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
